from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
from system_status import status

def generate_pdf_report(report_type="daily"):

    filename = f"{report_type}_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"

    c = canvas.Canvas(filename, pagesize=A4)

    c.setFont("Helvetica-Bold", 16)
    c.drawString(200, 800, "AI NETWORK REPORT")

    c.setFont("Helvetica", 12)
    c.drawString(50, 750, f"Report Type: {report_type}")
    c.drawString(50, 730, f"Date: {datetime.now()}")

    y = 700

    c.drawString(50, y, "SYSTEM STATUS:")
    y -= 30

    for device, state in status.items():
        c.drawString(70, y, f"{device}: {state}")
        y -= 20

    c.drawString(50, y-20, "Generated by AI Self-Healing System")

    c.save()

    return filename